spring-ai-alibaba/examples

CODE_OF_CONDUCT.md, CONTRIBUTION.md, README-zh.md, README.md, Roadmap-zh.md
> Add DashScope LLMs chat example
=> docs: add docs

CONTRIBUTION.md, README-zh.md, README.md
> Add DashScope LLMs chat example
=> fix: fix typo

spring-ai-alibaba-chat-example/dashscope/chat-client/pom.xml, spring-ai-alibaba-chat-example/dashscope/chat-model/pom.xml
- Fixed the issue that package budget operation failed
```shell
$ java -jar chat-model-1.0.0.jar
2024-12-18T21:47:43.051+08:00  INFO 16012 --- [spring-ai-alibaba-dashscope-chat-model-example] [           main] c.a.nacos.client.logging.NacosLogging    : Nacos Logging Adapter Builder: com.alibaba.nacos.logger.adapter.logback12.LogbackNacosLoggingAdapterBuilder
2024-12-18T21:47:43.065+08:00  INFO 16012 --- [spring-ai-alibaba-dashscope-chat-model-example] [           main] c.a.nacos.client.logging.NacosLogging    : Nacos Logging Adapter Builder: com.alibaba.nacos.logger.adapter.logback14.LogbackNacosLoggingAdapterBuilder
2024-12-18T21:47:43.066+08:00  INFO 16012 --- [spring-ai-alibaba-dashscope-chat-model-example] [           main] c.a.nacos.client.logging.NacosL
ogging    : Nacos Logging …
```
=> fix: fixed the issue that package budget operation failed

spring-ai-alibaba-stream-to-bean-example/pom.xml, spring-ai-alibaba-stream-to-bean-example/stream-to-bean/mvnw, spring-ai-alibaba-stream-to-bean-example/stream-to-bean/mvnw.cmd, spring-ai-alibaba-stream-to-bean-example/stream-to-bean/pom.xml, spring-ai-alibaba-stream-to-bean-example/stream-to-bean/src/main/java/com/alibaba/cloud/ai/example/stream/StreamToBeanApplication.java, spring-ai-alibaba-stream-to-bean-example/stream-to-bean/src/main/java/com/alibaba/cloud/ai/example/stream/StreamToBeanController.java, spring-ai-alibaba-stream-to-bean-example/stream-to-bean/src/main/java/com/alibaba/cloud/ai/example/stream/StreamToBeanEntity.java, spring-ai-alibaba-stream-to-bean-example/stream-to-bean/src/main/resources/application.yml
> Add stream to bean example
fix https://github.com/alibaba/spring-ai-alibaba/issues/299
=> feat: add example of stream to bean

spring-ai-alibaba-chat-example/openai-chat/openai-chat-client/src/main/resources/application.yml, spring-ai-alibaba-chat-example/openai-chat/openai-chat-model/src/main/resources/application.yml
添加了支持 OpenAI 兼容格式大模型的配置示例，特别是增加了字节火山引擎方舟大模型(Ark LLM)的配置模板。
1. 在 `application.yml` 中新增配置示例：
- 添加 API 密钥配置项
- 配置方舟大模型 API 基础地址
- 设置模型 ID 参数
- 配置 Chat 完成接口路径
为开发者提供更多的大模型接入选项，特别是针对想要使用国内大模型的用户，提供了完整的配置参考。
可以通过以下步骤验证配置：
1. 配置环境变量 `OPENAI_API_KEY` 和 `OPENAI_MODEL_ID`
2. 更新 `base-url` 为实际的接入点地址
3. 验证 Chat 接口调用是否正常
- 配置示例中的 API 地址需要替换为实际的接入点地址
- 模型 ID 需要替换为实际的接入点 ID
- API 密钥需要通过环境变量注入
- [Spring AI 官方文档](https://docs.spring.io/spring-ai/reference/)
- [火山引擎方舟大模型文档](https://www.volcengine.com/docs/82379)
---
> 如有任何问题或建议，欢迎在 PR 中讨论 🙏
Added configuration examples for OpenAI-compatible models, specifically including the configuration template for ByteDance Ark LLM (Volcano Engine).
1. Added new configuration examples in `application.yml`:
- Added API key configuration
- Configured Ark LLM API base URL …
=> feat(config): 添加 OpenAI 兼容大模型配置示例 | Add configuration examples for OpenAI-compatible models

spring-ai-alibaba-chat-example/zhipuai-chat/pom.xml, spring-ai-alibaba-chat-example/zhipuai-chat/zhipuai-chat-client/README.md, spring-ai-alibaba-chat-example/zhipuai-chat/zhipuai-chat-client/pom.xml, spring-ai-alibaba-chat-example/zhipuai-chat/zhipuai-chat-client/src/main/java/com/alibaba/cloud/ai/example/chat/zhipuai/ZhiPuAiChatClientApplication.java, spring-ai-alibaba-chat-example/zhipuai-chat/zhipuai-chat-client/src/main/java/com/alibaba/cloud/ai/example/chat/zhipuai/controller/ZhiPuAiClientController.java, spring-ai-alibaba-chat-example/zhipuai-chat/zhipuai-chat-client/src/main/resources/application.yml, spring-ai-alibaba-chat-example/zhipuai-chat/zhipuai-chat-model/README.md, spring-ai-alibaba-chat-example/zhipuai-chat/zhipuai-chat-model/pom.xml, spring-ai-alibaba-chat-example/zhipuai-chat/zhipuai-chat-model/src/main/java/com/alibaba/cloud/ai/example/chat/zhipuai/ZhiPuAiChatModelApplication.java, spring-ai-alibaba-chat-example/zhipuai-chat/zhipuai-chat-model/src/main/java/com/alibaba/cloud/ai/example/chat/zhipuai/controller/ZhiPuAiChatModelController.java, spring-ai-alibaba-chat-example/zhipuai-chat/zhipuai-chat-model/src/main/resources/application.yml
=> 1.add ZhiPuAi example

spring-ai-alibaba-chat-example/openai-chat/openai-chat-model/src/main/java/com/alibaba/cloud/ai/example/chat/openai/controller/OpenAiChatModelController.java, spring-ai-alibaba-chat-example/zhipuai-chat/zhipuai-chat-model/src/main/java/com/alibaba/cloud/ai/example/chat/zhipuai/controller/ZhiPuAiChatModelController.java, spring-ai-alibaba-chat-example/zhipuai-chat/zhipuai-chat-model/src/main/resources/application.yml
fix OpenAI and ZhiPuAI stream chat
=> fix: fix OpenAI and ZhiPuAI stream chat

docker-compose/milvus/docker-compose.yml, spring-ai-alibaba-rag-milvus-example/README.md
> Add Some Essential Remark of Milvus 
> Add Docker Compose file  of Milvus
=> Add Some Essential Remark & Add Docker Compose file of Milvus  

spring-ai-alibaba-chat-example/deepseek-chat/deepseek-chat-model/src/main/resources/application.yml
> Add deepseek-chat-model project's application config.
=> add deepseek-chat-model project's application config.

spring-ai-alibaba-structured-example/src/main/java/com/alibaba/cloud/ai/example/outparser/stream/StreamToJsonController.java
=> feat: add json output example

spring-ai-alibaba-more-platform-and-model-example/pom.xml, spring-ai-alibaba-more-platform-and-model-example/src/main/java/com/alibaba/ai/examples/controller/MorePlatformController.java, spring-ai-alibaba-more-platform-and-model-example/src/main/resources/application.yml
=> feat:add openai bean.

spring-ai-alibaba-rag-example/rag-example/pom.xml
修复 es如下版本问题；java.lang.NoSuchMethodError: 'co.elastic.clients.elasticsearch._types.KnnSearch$Builder co.elastic.clients.elasticsearch._types.KnnSearch$Builder.k(java.lang.Long)'
=> 修复 es版本问题 

spring-ai-alibaba-more-platform-and-model-example/README.md, spring-ai-alibaba-more-platform-and-model-example/src/main/java/com/alibaba/ai/examples/controller/client/MoreModelChatClientController.java, spring-ai-alibaba-more-platform-and-model-example/src/main/java/com/alibaba/ai/examples/controller/client/MorePlatformChatClientController.java, spring-ai-alibaba-more-platform-and-model-example/src/main/java/com/alibaba/ai/examples/controller/model/MoreModelCallController.java, spring-ai-alibaba-more-platform-and-model-example/src/main/java/com/alibaba/ai/examples/controller/model/MorePlatformController.java
- Add more model and platform chatclient t examples
=> feat: add more model and platform chatclient t examples

spring-ai-alibaba-integration-example/backend/.gitignore, spring-ai-alibaba-integration-example/backend/pom.xml, spring-ai-alibaba-integration-example/backend/src/main/java/com/alibaba/cloud/ai/application/aop/UserIpAspect.java, spring-ai-alibaba-integration-example/backend/src/main/java/com/alibaba/cloud/ai/application/config/RestConfiguration.java, spring-ai-alibaba-integration-example/backend/src/main/java/com/alibaba/cloud/ai/application/controller/SAAChatController.java, spring-ai-alibaba-integration-example/backend/src/main/java/com/alibaba/cloud/ai/application/entity/User.java, spring-ai-alibaba-integration-example/backend/src/main/java/com/alibaba/cloud/ai/application/repository/UserRepository.java, spring-ai-alibaba-integration-example/backend/src/main/java/com/alibaba/cloud/ai/application/utils/TimeUtils.java, spring-ai-alibaba-integration-example/backend/src/main/resources/application-dev.yml, spring-ai-alibaba-integration-example/backend/src/main/resources/application-pord.yml
> Add DashScope LLMs chat example
=> feat: update playground code

spring-ai-alibaba-integration-example/frontend/package.json, spring-ai-alibaba-integration-example/frontend/patches/@ant-design__x@1.0.4.patch, spring-ai-alibaba-integration-example/frontend/pnpm-lock.yaml, spring-ai-alibaba-integration-example/frontend/src/App.tsx, spring-ai-alibaba-integration-example/frontend/src/request.ts, spring-ai-alibaba-integration-example/frontend/vite.config.js
1. 添加聊天交互过程
2. 添加图片 + 文字的交互模式
3. 前端支持创建新聊天，并启动 ChatMemory
=> Add chat interaction capabilities

spring-ai-alibaba-function-calling-example/pom.xml, spring-ai-alibaba-rag-example/bailian-agent/pom.xml, spring-ai-alibaba-rag-example/bailian-rag-knowledge/pom.xml, spring-ai-alibaba-rag-example/pom.xml, spring-ai-alibaba-rag-example/rag-example/pom.xml, spring-ai-alibaba-rag-example/rag-milvus-example/pom.xml, spring-ai-alibaba-rag-example/rag-pgvector-example/pom.xml, spring-ai-alibaba-rag-example/web-search/pom.xml
>fix:update SpringAI version info based on parent
=> fix:update SpringAI version info based on parent

spring-ai-alibaba-rag-example/module-rag/pom.xml
> Add DashScope LLMs chat example
=> feat: add module-rag pom.xml

spring-ai-alibaba-integration-example/frontend/patches/@ant-design__x@1.0.4.patch, spring-ai-alibaba-integration-example/frontend/pnpm-lock.yaml, spring-ai-alibaba-integration-example/frontend/src/App.tsx
=> 解决多个会话切换问题

README.md
=> docs 文档细节问题

spring-ai-alibaba-integration-example/frontend/src/App.tsx
=> 简易的 <think> 标签处理

spring-ai-alibaba-mcp-example/starter-example/pom.xml, spring-ai-alibaba-mcp-example/starter-example/server/starter-stock-server/pom.xml, spring-ai-alibaba-mcp-example/starter-example/server/starter-stock-server/src/main/java/com/alibaba/spring/ai/example/stock/StockServerApplication.java, spring-ai-alibaba-mcp-example/starter-example/server/starter-stock-server/src/main/java/com/alibaba/spring/ai/example/stock/service/StockService.java, spring-ai-alibaba-mcp-example/starter-example/server/starter-stock-server/src/main/resources/application.yml, spring-ai-alibaba-mcp-example/starter-example/server/starter-stock-server/src/test/java/com/alibaba/spring/ai/example/stock/client/ClientStdio.java
Feat : Add an MCP server for querying stock information
=> Feat : Add an MCP server for querying stock information

spring-ai-alibaba-mcp-example/starter-example/server/starter-stock-server/src/main/java/com/alibaba/spring/ai/example/stock/service/StockService.java
移除了 StockService 类中未使用的 lombok.RequiredArgsConstructor 导入。
=> refactor: 移除 StockService 中的未使用导入

spring-ai-alibaba-scene-example/multi-model-chat/pom.xml, spring-ai-alibaba-translate-example/src/main/java/com/alibaba/example/translate/TranslateApplication.java
=> fix:修复编译错误

spring-ai-alibaba-playground/ui/src/api/mcp.ts, spring-ai-alibaba-playground/ui/src/menuPages/ChatPage/ChatConversationView.tsx, spring-ai-alibaba-playground/ui/src/menuPages/ChatPage/ChatLandingView.tsx, spring-ai-alibaba-playground/ui/src/menuPages/components/FunctionMenu/index.tsx, spring-ai-alibaba-playground/ui/src/menuPages/imageGenPage/ImageGenLandingView.tsx, spring-ai-alibaba-playground/ui/src/menuPages/mcpPage/McpConversationView.tsx, spring-ai-alibaba-playground/ui/src/menuPages/mcpPage/McpLandingView.tsx, spring-ai-alibaba-playground/ui/src/stores/conversation.store.ts
=> Playground: BugFix

spring-ai-alibaba-agent-example/playground-flight-booking/src/main/java/ai/spring/demo/ai/playground/services/CustomerSupportAssistant.java
defaultFunctions 方法过时了,修改成defaultTools
=> defaultFunctions 方法过时了,修改成defaultTools

spring-ai-alibaba-playground/ui/src/api/doc.ts, spring-ai-alibaba-playground/ui/src/menuPages/ChatPage/ChatConversationView.tsx, spring-ai-alibaba-playground/ui/src/menuPages/docSummaryPage/index.css, spring-ai-alibaba-playground/ui/src/menuPages/docSummaryPage/index.tsx
>  `添加文档总结页面，支持文件上传、链接上传、历史记录查看及重新生成功能。页面包含拖拽上传、文件类型验证、处理结果展示等功能，提升用户体验。`
=> Feat(docSummaryPage): 新增文档总结页面功能

spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/controller/SAAMcpController.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/entity/tools/ToolCallResp.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/service/SAAMcpService.java
Feat ： Add mcp tool calling observation in playground
=> Feat ： Add mcp tool calling observation in playground

spring-ai-alibaba-playground/ui/src/App.tsx, spring-ai-alibaba-playground/ui/src/api/base.ts, spring-ai-alibaba-playground/ui/src/api/chat.ts, spring-ai-alibaba-playground/ui/src/api/image.ts, spring-ai-alibaba-playground/ui/src/api/mcp.ts, spring-ai-alibaba-playground/ui/src/api/rag.ts, spring-ai-alibaba-playground/ui/src/const.tsx, spring-ai-alibaba-playground/ui/src/hooks.tsx, spring-ai-alibaba-playground/ui/src/menuPages/ChatPage/ChatConversationView.tsx, spring-ai-alibaba-playground/ui/src/menuPages/ChatPage/ChatLandingView.tsx, spring-ai-alibaba-playground/ui/src/menuPages/ChatPage/style.ts, spring-ai-alibaba-playground/ui/src/menuPages/components/FunctionMenu/index.tsx, spring-ai-alibaba-playground/ui/src/menuPages/components/RequestBubble/style.ts, spring-ai-alibaba-playground/ui/src/menuPages/components/ResponseBubble/components/CopyButton/index.tsx, spring-ai-alibaba-playground/ui/src/menuPages/components/ResponseBubble/components/PureText/index.tsx, spring-ai-alibaba-playground/ui/src/menuPages/components/ResponseBubble/index.tsx, spring-ai-alibaba-playground/ui/src/menuPages/components/ResponseBubble/style.ts, spring-ai-alibaba-playground/ui/src/menuPages/components/ResponseBubble/utils.tsx, spring-ai-alibaba-playground/ui/src/menuPages/functionCallingPage/FunctionCallingConversationView.tsx, spring-ai-alibaba-playground/ui/src/menuPages/imageGenPage/ImageGenConversationView.tsx, spring-ai-alibaba-playground/ui/src/menuPages/imageGenPage/ImageGenLandingView.tsx, spring-ai-alibaba-playground/ui/src/menuPages/mcpPage/McpLandingView.tsx, spring-ai-alibaba-playground/ui/src/menuPages/ragPage/components/CreateKnowledgeBaseModal/index.tsx, spring-ai-alibaba-playground/ui/src/menuPages/ragPage/components/KnowledgeBaseList/index.tsx, spring-ai-alibaba-playground/ui/src/menuPages/ragPage/index.tsx, spring-ai-alibaba-playground/ui/src/stores/conversation.store.ts, spring-ai-alibaba-playground/ui/src/style.ts, spring-ai-alibaba-playground/ui/src/utils.ts
=> [WIP] improve playground code

spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/config/mcp/McpStdioTransportConfigurationBeanPostProcessor.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/config/mcp/SyncMcpToolCallbackWrapper.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/mcp/McpServerUtils.java, spring-ai-alibaba-playground/src/main/resources/mcp-config.yml
=> feat: fix mcp tools list bug

spring-ai-alibaba-mcp-example/starter-example/server/starter-webflux-server/README.md
> 更新  starter-webflux-server  的 README.md
=> docs: update README with code examples and MCP settings

spring-ai-alibaba-mcp-example/starter-example/server/starter-stdio-server/src/test/java/org/springframework/ai/mcp/sample/client/ClientStdio.java
- reslove https://github.com/alibaba/spring-ai-alibaba/issues/658
=> fix mcp-stdio-server-example unit test exception

spring-ai-alibaba-tool-calling-example/pom.xml, spring-ai-alibaba-tool-calling-example/src/main/java/com/alibaba/cloud/ai/toolcall/controller/MicrosoftTranslateController.java, spring-ai-alibaba-tool-calling-example/src/main/resources/application.yml
add toolcalling microsoft translate example
link: https://github.com/alibaba/spring-ai-alibaba/pull/758
=> add toolcalling microsoft translate example

spring-ai-alibaba-graph-example/src/main/java/com/alibaba/example/Application.java, spring-ai-alibaba-graph-example/src/main/java/com/alibaba/example/controller/ParallelController.java, spring-ai-alibaba-graph-example/src/main/java/com/alibaba/example/graph/conf/ParallelGraphConfiguration.java, spring-ai-alibaba-graph-example/src/main/java/com/alibaba/example/graph/conf/WritingAssistantAutoconfiguration.java
=> feat: add parallel node example

spring-ai-alibaba-playground/Dockerfile, spring-ai-alibaba-playground/build-and-run.sh, spring-ai-alibaba-playground/docker-README.md, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/config/rag/VectorStoreInitializer.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/mcp/McpServerUtils.java, spring-ai-alibaba-playground/src/main/resources/mcp-config.yml
feat: add playground Dockerfile
=> feat: add playground Dockerfile

spring-ai-alibaba-mcp-example/pom.xml, spring-ai-alibaba-mcp-example/starter-example/client/nacos-mcp-client-example/README.md, spring-ai-alibaba-mcp-example/starter-example/client/nacos-mcp-client-example/pom.xml, spring-ai-alibaba-mcp-example/starter-example/client/nacos-mcp-client-example/src/main/java/com/alibaba/cloud/ai/NacosMcpSseClientApplication.java, spring-ai-alibaba-mcp-example/starter-example/client/nacos-mcp-client-example/src/main/resources/application.yml, spring-ai-alibaba-mcp-example/starter-example/pom.xml, spring-ai-alibaba-mcp-example/starter-example/server/nacos-dynamic-mcp-server-example/pom.xml
=> add nacos-client example

spring-ai-alibaba-chat-memory-example/pom.xml, spring-ai-alibaba-chat-memory-example/src/main/java/com/alibaba/example/chatmemory/config/AppConfig.java, spring-ai-alibaba-chat-memory-example/src/main/java/com/alibaba/example/chatmemory/controller/ChatMemoryController.java
1. the latest dependencies of redis and jdbc memory
2. add new example of redis memory
=> fix:the latest dependencies of redis and jdbc memory

spring-ai-alibaba-mcp-example/starter-example/client/nacos-mcp-client-example/src/main/resources/application.yml, spring-ai-alibaba-mcp-example/starter-example/client/starter-default-client/src/main/resources/application.yml, spring-ai-alibaba-mcp-example/starter-example/client/starter-streamable-client/src/main/resources/application.yml, spring-ai-alibaba-mcp-example/starter-example/client/starter-webflux-client/src/main/resources/application.yml
=> Fix: Standardize AI service environment variable naming convention

spring-ai-alibaba-chat-memory-example/src/main/java/com/alibaba/example/chatmemory/config/AppConfig.java, spring-ai-alibaba-chat-memory-example/src/main/java/com/alibaba/example/chatmemory/controller/ChatMemoryController.java, spring-ai-alibaba-chat-memory-example/src/main/resources/application.yml, spring-ai-alibaba-playground/pom.xml, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/service/SAARAGService.java, spring-ai-alibaba-rag-example/rag-milvus-example/pom.xml, spring-ai-alibaba-rag-example/rag-milvus-example/src/main/java/com/alibaba/cloud/ai/example/rag/controller/RagController.java, spring-ai-alibaba-usecase-example/spring-ai-alibaba-classification-grading-example/src/main/java/com/alibaba/cloud/ai/example/dcg/service/ClassificationAssistant.java
=> fix memory example and playground QuestionAnswerAdvisor

spring-ai-alibaba-structured-example/src/main/java/com/alibaba/cloud/ai/example/outparser/controller/BeanController.java
complete the structured-example module's todo
=> feat: complete the structured-example module's todo

spring-ai-alibaba-graph-example/src/main/java/com/alibaba/example/controller/ParallelController.java, spring-ai-alibaba-graph-example/src/main/java/com/alibaba/example/controller/WritingAssistantController.java, spring-ai-alibaba-graph-example/src/main/java/com/alibaba/example/graph/conf/ParallelGraphConfiguration.java, spring-ai-alibaba-graph-example/src/main/java/com/alibaba/example/graph/conf/WritingAssistantAutoconfiguration.java
=> fix graph example

spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/advisor/ReasoningContentAdvisor.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/config/AppConfiguration.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/rag/WebSearchRetriever.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/rag/data/DataClean.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/rag/postretrieval/DashScopeDocumentRanker.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/service/SAAChatService.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/service/SAAImageService.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/service/SAARAGService.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/service/SAASummarizerService.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/service/SAAVideoService.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/service/SAAWebSearchService.java
新版本1.0.0-RC1.1更新后，playground产生了部分类缺失和构造函数参数不再匹配。
我主要修改了chatMemory涉及的参数。
TODO标注了部分类缺失和不匹配的构造函数，这部分确实得靠大佬们来修修了。
=> fix:Marking the lack Class & fix ChatMemory params

spring-ai-alibaba-chat-memory-example/pom.xml, spring-ai-alibaba-chat-memory-example/src/main/java/com/alibaba/example/chatmemory/config/AppConfig.java
=> fix chat memory example

spring-ai-alibaba-tool-calling-example/pom.xml, spring-ai-alibaba-tool-calling-example/src/main/java/com/alibaba/cloud/ai/toolcall/controller/GithubtoolkitController.java, spring-ai-alibaba-tool-calling-example/src/main/java/com/alibaba/cloud/ai/toolcall/controller/TimeController.java, spring-ai-alibaba-tool-calling-example/src/main/java/com/alibaba/cloud/ai/toolcall/controller/WeatherController.java, spring-ai-alibaba-tool-calling-example/src/main/resources/application.yml
添加了githubtoolkit 的使用示例，并且规范了 weather 、time 工具的方法名
=> feat: add githubtoolkit example

spring-ai-alibaba-playground/pom.xml, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/advisor/ReasoningContentAdvisor.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/config/WeSearchConfiguration.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/rag/WebSearchRetriever.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/rag/data/DataClean.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/rag/postretrieval/DashScopeDocumentRanker.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/service/SAAImageService.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/service/SAAVideoService.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/service/SAAWebSearchService.java
=> fix saa play ground

spring-ai-alibaba-playground/pom.xml
=> [fix] fix play ground

spring-ai-alibaba-playground/pom.xml, spring-ai-alibaba-tool-calling-example/README.md, spring-ai-alibaba-tool-calling-example/src/main/resources/application.yml
The playground project is missing a groupId, causing Maven build errors.
=> fix: groupId

spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-starter-example/server/mcp-stdio-server-example/pom.xml, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-starter-example/server/starter-stock-server/pom.xml
fix mcp examples
fix mcp dependencies
=> fix mcp examples

spring-ai-alibaba-rag-example/spring-ai-alibaba-vector-databases-example/vector-opensearch-example/pom.xml
=> fix example deps

spring-ai-alibaba-multi-model-example/ark-multi-model/src/main/resources/application.yml, spring-ai-alibaba-rag-example/bailian-agent/src/main/java/com/alibaba/cloud/ai/example/rag/agent/config/BailianAutoconfiguration.java, spring-ai-alibaba-rag-example/bailian-rag-knowledge/src/main/java/com/alibaba/cloud/ai/example/rag/knowledge/config/BailianAutoconfiguration.java
=> fix dashscope api

spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-starter-example/client/mcp-webflux-client-example/src/main/java/org/springframework/ai/mcp/samples/client/Application.java
=> fix mcp client

spring-ai-alibaba-chat-example/qwq-chat/src/main/java/com/alibaba/cloud/ai/example/chat/qwq/controller/QWQChatClientController.java
=> enable thinking demo

spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-build-example/pom.xml
fix mvn install error 
```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.alibaba.cloud.ai:spring-ai-alibaba-mcp-build-example:1.0.0: The following artifacts could not be resolved: com.alibaba.cloud.ai:spring-ai-alibaba-mcp-example:pom:1.0.0 (absent): com.alibaba.cloud.ai:spring-ai-alibaba-mcp-example:pom:1.0.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 6, column 10
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: …
```
=> fix : update parent version to use dynamic revision

spring-ai-alibaba-playground/pom.xml, spring-ai-alibaba-playground/src/main/resources/mcp-config.yml
=> feat: update playground

spring-ai-alibaba-structured-example/src/main/java/com/alibaba/cloud/ai/example/outparser/controller/BeanController.java, spring-ai-alibaba-structured-example/src/main/java/com/alibaba/cloud/ai/example/outparser/controller/MapListController.java
=> feat(outparse): optimize

spring-ai-alibaba-graph-example/src/main/java/com/alibaba/example/controller/GraphController.java, spring-ai-alibaba-graph-example/src/main/java/com/alibaba/example/graph/conf/ComplexSupportGraphBuilder.java, spring-ai-alibaba-graph-example/src/main/java/com/alibaba/example/graph/conf/VectorStoreConfig.java, spring-ai-alibaba-graph-example/src/main/java/com/alibaba/example/graph/node/AnswerNode.java
`mvn package` exception:
```
[ERROR]  * D:\IDEAProjects\spring-ai-alibaba-examples\spring-ai-alibaba-graph-example\src\main\java\com\alibaba\example\controller\GraphController.java
[ERROR]  * D:\IDEAProjects\spring-ai-alibaba-examples\spring-ai-alibaba-graph-example\src\main\java\com\alibaba\example\graph\conf\ComplexSupportGraphBuilder.java
[ERROR]  * D:\IDEAProjects\spring-ai-alibaba-examples\spring-ai-alibaba-graph-example\src\main\java\com\alibaba\example\graph\conf\VectorStoreConfig.java
[ERROR]  * D:\IDEAProjects\spring-ai-alibaba-examples\spring-ai-alibaba-graph-example\src\main\java\com\alibaba\example\graph\node\AnswerNode.java
[ERROR] 
[ERROR] Run `spring-javaformat:apply` to fix.
```
=> improve: format code for improved readability and consistency

spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-nacos-example/server/mcp-nacos-registry-example/src/main/java/com/alibaba/cloud/ai/example/Application.java
AutoConfig class modify, example also need to be modified simultaneously
Synchronous modify:
https://github.com/zhangshenghang/spring-ai-alibaba/commit/f4bfdf596d1a194d3e155d09519ac0d3f3cfeb16
=> fix: update Nacos configuration class

spring-ai-alibaba-nl2sql-example/chat/src/main/java/com.alibaba.cloud.ai.example/controller/Nl2sqlController.java
adapt:
- https://github.com/alibaba/spring-ai-alibaba/pull/1288
=> feat: add Nl2sqlController for handling NL2SQL search queries

spring-ai-alibaba-nl2sql-example/chat/src/main/java/com.alibaba.cloud.ai.example/Application.java, spring-ai-alibaba-nl2sql-example/chat/src/main/java/com.alibaba.cloud.ai.example/controller/AnalyticNl2SqlController.java, spring-ai-alibaba-nl2sql-example/chat/src/main/java/com.alibaba.cloud.ai.example/controller/Nl2sqlForGraphController.java, spring-ai-alibaba-nl2sql-example/chat/src/main/java/com.alibaba.cloud.ai.example/controller/SimpleChatController.java
=> feat(nl2sql): add AnalyticNl2SqlController and refactor existing controllers

spring-ai-alibaba-chat-example/azure-openai-chat/pom.xml
=> fix pom issues

spring-ai-alibaba-nl2sql-example/chat/pom.xml, spring-ai-alibaba-nl2sql-example/vector-management/pom.xml
=> clear  duplicate deps

spring-ai-alibaba-graph-example/human-node/pom.xml, spring-ai-alibaba-graph-example/human-node/src/main/java/com/alibaba/cloud/ai/graph/HumanNodeApplication.java, spring-ai-alibaba-graph-example/human-node/src/main/java/com/alibaba/cloud/ai/graph/config/GraphHumanConfiguration.java, spring-ai-alibaba-graph-example/human-node/src/main/java/com/alibaba/cloud/ai/graph/controller/GraphHumanController.java, spring-ai-alibaba-graph-example/human-node/src/main/java/com/alibaba/cloud/ai/graph/controller/GraphProcess/GraphProcess.java, spring-ai-alibaba-graph-example/human-node/src/main/java/com/alibaba/cloud/ai/graph/dispatcher/HumanFeedbackDispatcher.java, spring-ai-alibaba-graph-example/human-node/src/main/java/com/alibaba/cloud/ai/graph/node/ExpanderNode.java, spring-ai-alibaba-graph-example/human-node/src/main/java/com/alibaba/cloud/ai/graph/node/HumanFeedbackNode.java, spring-ai-alibaba-graph-example/human-node/src/main/java/com/alibaba/cloud/ai/graph/node/TranslateNode.java, spring-ai-alibaba-graph-example/human-node/src/main/resources/application.yml, spring-ai-alibaba-graph-example/mcp-node/pom.xml, spring-ai-alibaba-graph-example/mcp-node/src/main/java/com/alibaba/cloud/ai/graph/McpNodeApplication.java, spring-ai-alibaba-graph-example/mcp-node/src/main/java/com/alibaba/cloud/ai/graph/config/McpGaphConfiguration.java, spring-ai-alibaba-graph-example/mcp-node/src/main/java/com/alibaba/cloud/ai/graph/config/McpNodeProperties.java, spring-ai-alibaba-graph-example/mcp-node/src/main/java/com/alibaba/cloud/ai/graph/controller/McpController.java, spring-ai-alibaba-graph-example/mcp-node/src/main/java/com/alibaba/cloud/ai/graph/node/McpNode.java, spring-ai-alibaba-graph-example/mcp-node/src/main/java/com/alibaba/cloud/ai/graph/tool/McpClientToolCallbackProvider.java, spring-ai-alibaba-graph-example/mcp-node/src/main/resources/application.yml, spring-ai-alibaba-graph-example/pom.xml, spring-ai-alibaba-graph-example/stream-node/pom.xml, spring-ai-alibaba-graph-example/stream-node/src/main/java/com/alibaba/cloud/ai/graph/StreamNodeApplication.java, spring-ai-alibaba-graph-example/stream-node/src/main/java/com/alibaba/cloud/ai/graph/config/GraphNodeStreamConfiguration.java, spring-ai-alibaba-graph-example/stream-node/src/main/java/com/alibaba/cloud/ai/graph/controller/GraphProcess/GraphProcess.java, spring-ai-alibaba-graph-example/stream-node/src/main/java/com/alibaba/cloud/ai/graph/controller/GraphStreamController.java, spring-ai-alibaba-graph-example/stream-node/src/main/java/com/alibaba/cloud/ai/graph/node/ExpanderNode.java, spring-ai-alibaba-graph-example/stream-node/src/main/resources/application.yml
增加三个graph例子
1. 节点的流式输出
2. 分配指定mcp给指定节点
3. 人类反馈，中断、恢复
=> Feat graph basic

spring-ai-alibaba-mcp-example/pom.xml, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/README.md, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/client/mcp-auth-client/pom.xml, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/client/mcp-auth-client/src/main/java/com/alibaba/cloud/ai/mcp/client/AuthClientApplication.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/client/mcp-auth-client/src/main/java/org/springframework/ai/mcp/client/autoconfigure/SseWebFluxTransportAutoConfiguration.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/client/mcp-auth-client/src/main/java/org/springframework/ai/mcp/client/autoconfigure/properties/McpSseClientProperties.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/client/mcp-auth-client/src/main/resources/application.yml, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/pom.xml, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/restufl-example/pom.xml, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/restufl-example/src/main/java/com/alibaba/cloud/ai/mcp/restful/RestfulApplication.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/restufl-example/src/main/java/com/alibaba/cloud/ai/mcp/restful/controller/TimeController.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/restufl-example/src/main/java/com/alibaba/cloud/ai/mcp/restful/utils/ZoneUtils.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/restufl-example/src/main/resources/application.yml, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/server/mcp-auth-server/pom.xml, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/server/mcp-auth-server/src/main/java/com/alibaba/cloud/ai/mcp/server/AuthServerApplication.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/server/mcp-auth-server/src/main/java/com/alibaba/cloud/ai/mcp/server/model/Parameter.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/server/mcp-auth-server/src/main/java/com/alibaba/cloud/ai/mcp/server/model/RestfulModel.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/server/mcp-auth-server/src/main/java/com/alibaba/cloud/ai/mcp/server/parse/ParseRestful.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/server/mcp-auth-server/src/main/java/com/alibaba/cloud/ai/mcp/server/util/ApplicationContextHolder.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/server/mcp-auth-server/src/main/java/com/alibaba/cloud/ai/mcp/server/util/JSONSchemaUtil.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/server/mcp-auth-server/src/main/java/io/modelcontextprotocol/server/transport/WebFluxSseServerTransportProvider.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/server/mcp-auth-server/src/main/java/org/springframework/ai/mcp/McpRestfulToolCallback.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/server/mcp-auth-server/src/main/java/org/springframework/ai/mcp/McpRestfulToolCallbackProvider.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/server/mcp-auth-server/src/main/java/org/springframework/ai/mcp/RestfulToolDefinition.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-auth-example/server/mcp-auth-server/src/main/resources/application.yml
=> add mcp-auth exmaple

spring-ai-alibaba-nl2sql-example/chat/README.md
- resolve https://github.com/alibaba/spring-ai-alibaba/issues/1427
=> update nl2sql readme

spring-ai-alibaba-graph-example/graph-observability-langfuse/README.md, spring-ai-alibaba-graph-example/graph-observability-langfuse/pom.xml, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/ObservabilityApplication.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/config/GraphConfiguration.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/controller/GraphController.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/controller/GraphStreamController.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/controller/process/GraphProcess.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/resources/application.yml, spring-ai-alibaba-graph-example/pom.xml
Feat: add graph observation example with langfuse
=> add graph observation example with langfuse

spring-ai-alibaba-graph-example/pom.xml
=> fix graph example module

spring-ai-alibaba-graph-example/workflow-writing-assistant/src/main/java/com/alibaba/example/controller/GraphController.java, spring-ai-alibaba-graph-example/workflow-writing-assistant/src/main/java/com/alibaba/example/controller/ParallelController.java, spring-ai-alibaba-graph-example/workflow-writing-assistant/src/main/java/com/alibaba/example/graph/conf/ComplexSupportGraphBuilder.java, spring-ai-alibaba-graph-example/workflow-writing-assistant/src/main/java/com/alibaba/example/graph/conf/WritingAssistantAutoconfiguration.java, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-nacos-example/server/mcp-nacos-registry-example/src/main/java/com/alibaba/cloud/ai/example/Application.java, spring-ai-alibaba-rag-example/rag-openai-dashscope-pgvector-example/pom.xml
=> fix some compile error

spring-ai-alibaba-graph-example/parallel-node/src/main/java/com/alibaba/cloud/ai/graph/node/CollectorNode.java, spring-ai-alibaba-graph-example/parallel-node/src/main/java/com/alibaba/cloud/ai/graph/node/DispatcherNode.java, spring-ai-alibaba-graph-example/parallel-node/src/main/java/com/alibaba/cloud/ai/graph/node/ExpanderNode.java, spring-ai-alibaba-graph-example/parallel-node/src/main/java/com/alibaba/cloud/ai/graph/node/TranslateNode.java
fix parallel node example without nodeactions
**REALLY SORRY FOR THAT T T**
=> fix(graph): fix parallel node example without nodeactions

spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/node/ChatNode.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/node/SimpleSubGraph.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/node/StreamingChatNode.java
fix missing node for graph langfuse example
**REALLY SORRY FOR THAT AGAIN T T**
=> fix(graph): fix missing node for graph langfuse example

spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/controller/GraphStreamController.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/controller/process/GraphProcess.java
=> fix graph stream observation example module

spring-ai-alibaba-multi-model-example/dashscope-multi-model/src/main/java/com/alibaba/cloud/ai/example/multi/controller/MultiModelController.java
Feat: add dashscope multimodality audio example
添加百炼大模型多模态音频输入样例
- 新增 /audio 接口，用于处理音频内容描述请求
- 实现了从音频文件中提取内容并生成描述文本的功能
- 使用了 qwen-audio-turbo-latest 模型进行音频内容理解
=> feat(dashscope-multi-model): add dashscope multimodality audio example

spring-ai-alibaba-graph-example/graph-observability-langfuse/pom.xml, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/config/GraphConfiguration.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/controller/GraphStreamController.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/controller/process/GraphProcess.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/node/ChatNode.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/node/SimpleSubGraph.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/node/StreamingChatNode.java
=> fix graph observation example stream

spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/config/GraphConfiguration.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/controller/GraphController.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/controller/process/GraphProcess.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/node/ChatNode.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/node/MergeNode.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/node/SimpleSubGraph.java, spring-ai-alibaba-graph-example/graph-observability-langfuse/src/main/java/com/alibaba/cloud/ai/graph/node/StreamingChatNode.java
fix graph observation example subgraph
=> fix graph observation example subgraph

spring-ai-alibaba-playground/pom.xml, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/SAAPlayGroundApplication.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/config/rag/SimpleVectorStoreConfiguration.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/controller/SAAChatController.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/controller/SAAVideoController.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/controller/SAAWebSearchController.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/entity/dashscope/ChatResponseDTO.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/service/ISAAWebSearchService.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/service/SAADashScopeWebSearchService.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/service/SAAVideoService.java, spring-ai-alibaba-playground/src/main/java/com/alibaba/cloud/ai/application/service/SAAWebSearchService.java, spring-ai-alibaba-playground/src/main/resources/application.yml
-  Add dashscope web search and gen video support
=> feat: add dashscope web search and gen video support

spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-nacos-example/server/mcp-nacos-gateway-example/README.md, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-nacos-example/server/mcp-nacos-gateway-example/pom.xml, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-nacos-example/server/mcp-nacos-gateway-example/src/main/resources/application.yml
link : https://github.com/alibaba/spring-ai-alibaba/pull/2023
=> feat: enhance MCP gateway configuration and documentation

spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-nacos-example/server/mcp-nacos-gateway-example/pom.xml, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-nacos-example/server/mcp-nacos-gateway-example/src/main/resources/application.yml, spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-nacos-example/server/mcp-nacos-register-example/pom.xml
=> Feat: mcp gateway router demo

spring-ai-alibaba-mcp-example/spring-ai-alibaba-mcp-nacos-example/server/mcp-nacos-gateway-example/src/main/java/com/alibaba/cloud/ai/example/controller/RouterController.java
=> feat: add mcp router controller demo

spring-ai-alibaba-graph-example/chatflow/src/main/java/com/alibaba/example/conf/TodoChatFlowFactory.java, spring-ai-alibaba-graph-example/chatflow/src/main/java/com/alibaba/example/conf/TodoSubGraphFactory.java
fix(graph): fix chatflow placeholder
在 `graph-example` 下的 **chatflow** 项目中，占位符使用过多，导致输出被错误截取。  
本 PR 修复了占位符问题，确保输出内容能够完整展示。
=> fix(graph): fix placeholder

spring-ai-alibaba-mem0-example/src/main/java/com/alibaba/mem0/example/controller/Mem0MemoryController.java
=> fix mem0 memory example import packages
